# Install Delinea Client package
- name: Linux OS family
  when: ansible_os_family in ["Debian", "RedHat", "Suse"]
  block:
    - name: Check if CentrifyCC is installed
      package_facts:

    - name: Install CentrifyCC package 
      include_tasks: "install-{{ ansible_os_family|lower }}.yml"
      when: '"centrifycc" not in ansible_facts.packages|lower'
  
- name: Windows OS family
  when: ansible_os_family == "Windows"
  block:
    - name: Check if Delinea Server Suite Agent is installed
      win_reg_stat:
        path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{43A16456-62CD-45A2-B2DF-743BA7A56894}
      register: cagent_installed
      
    - name: Install CAgent package
      include_tasks: "install-windows.yml"
      when: not cagent_installed.exists