# Remove Delinea Client package
- name: Remove CentrifyCC package
  become: true
  yum:
    name: CentrifyCC
    state: absent

- name: Delete Delinea Repo
  become: true
  file:
    path: /etc/yum.repos.d/centrify-rpm-redhat.repo
    state: absent
