# Remove Delinea Client package
- name: Remove CentrifyCC package
  zypper:
    name: CentrifyCC
    state: absent

- name: Delete Delinea Repo
  file:
    path: /etc/zypp/repos.d/centrify-rpm-suse.repo 
    state: absent
