# Remove Delinea Client package
- name: Linux OS family
  when: ansible_os_family in ["Debian", "RedHat", "Suse"]
  block:
    - name: Check if CentrifyCC is installed
      package_facts:

    - name: Remove Delinea Client package
      when: '"centrifycc" in ansible_facts.packages|lower'
      block:
        - name: Unenroll before removing CentrifyCC package
          include_tasks: unenroll.yml

        - name: Remove CentrifyCC package
          include_tasks: "remove-{{ ansible_os_family|lower }}.yml"

- name: Windows OS family
  when: ansible_os_family == "Windows"
  block:
    - name: Check if Delinea Server Suite Agent is installed
      win_reg_stat:
        path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{43A16456-62CD-45A2-B2DF-743BA7A56894}
      register: cagent_installed

    - name: Remove Delinea Client package
      when: cagent_installed.exists
      block:
        - name: Unenroll before removing Delinea Server Suite Agent package
          include_tasks: unenroll.yml
          when: cinfo_cmd.rc == 0

        - name: Remove Delinea Server Suite Agent package
          include_tasks: "remove-windows.yml"
