# Install on Suse family using Zypper
- name: Check if Delinea repo exists
  stat:
    path: /etc/zypp/repos.d/centrify-rpm-suse.repo
  register: filecheck

- name: Create Delinea repo if it doesn't exist
  when: not filecheck.stat.exists
  shell: curl -1sLf 'https://cloudrepo.centrify.com/{{ delinea_suse_urltoken }}/rpm-suse/cfg/setup/bash.rpm.sh' | sudo -E bash
  args:
    warn: false

- name: Install Delinea Audit Agent package
  zypper:
    name: CentrifyDA
    state: latest
