# Unenroll computer from Delinea Audit
- name: Linux OS family
  block:
  
    - name: Check if computer is enrolled to Delinea Audit & Monitoring Service
      command: dainfo
      register: dainfo_cmd
      changed_when: dainfo_cmd.rc == 0
      failed_when:
        - dainfo_cmd.rc != 10
        - dainfo_cmd.rc != 2
        - dainfo_cmd.rc != 0

    - name: Remove computer from Delinea Audit & Monitoring Service
      command: dacontrol --disable
      become: yes
      when: dainfo_cmd.rc == 0

  when: ansible_os_family in ["Debian", "RedHat", "Suse"]
  
#- name: Windows OS family
#block:
#
# >>> Delinea Audit & Monitoring is managed using Group Policies on Windows systems
#  
#when: ansible_os_family == "Windows"
