# Install on RedHat family using Yum
- name: Check if Delinea repo exists
  stat:
    path: /etc/yum.repos.d/centrify-rpm-redhat.repo
  register: filecheck

- name: Create Delinea repo if it doesn't exist
  shell: curl -1sLf 'https://cloudrepo.centrify.com/{{ delinea_redhat_urltoken }}/rpm-redhat/cfg/setup/bash.rpm.sh' | sudo -E bash
  args:
    warn: false
  when: not filecheck.stat.exists

- name: Install Delinea Server Suite Agent package
  yum:
    name: CentrifyDC
    state: latest
